export const EXPECTED_SCHEMA_MIGRATIONS = [
  { version: 1, name: "m0_foundation" },
  { version: 2, name: "append_only_evidence" },
  { version: 3, name: "ipca_item_provenance" },
  { version: 4, name: "classification_audit" },
  { version: 5, name: "batch_commitments" },
  { version: 6, name: "exploration_attempt_evidence" },
  { version: 7, name: "healing_event_idempotency" },
  { version: 8, name: "healing_worker_budget_reservations" },
  { version: 9, name: "healing_exploration_recovery" },
  { version: 10, name: "exploration_recovery_adjustments" },
  { version: 11, name: "collection_integrity" },
  { version: 12, name: "retailer_state_history" },
  { version: 13, name: "strategy_validation_evidence" },
  { version: 14, name: "strategy_validation_authorization" },
  { version: 15, name: "runtime_safety_reconciliation" },
  { version: 16, name: "discovery_tier_semantics" },
  { version: 17, name: "operator_catalog_seeds" },
  { version: 18, name: "classification_shape_recovery" },
  { version: 19, name: "classification_measurement_scope" },
  { version: 20, name: "product_url_identity" },
] as const;
